// Generated by: main
// TypeWriter: rx
// Directive: +gen on Rect

package lib

import (
	"context"
	sync "sync"
)

// RxRect is the reactive wrapper for Rect
type RxRect struct {
	value       Rect
	lock        sync.RWMutex
	handles     chan int
	subscribers []chan<- Rect
}

// NewRxRect creates a new reactive object for the initial value of Rect
func NewRxRect(v Rect) *RxRect {
	return &RxRect{
		value:   v,
		handles: make(chan int, 10),
	}
}

// Get gets the Rect
func (rx *RxRect) Get() Rect {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the Rect and notifies subscribers
func (rx *RxRect) Set(v Rect) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v
	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the Rect
func (rx *RxRect) Subscribe() *RxRectSubscriber {
	c := make(chan Rect)
	s := &RxRectSubscriber{
		C:      c,
		parent: rx,
	}
	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}
	rx.lock.Unlock()
	return s
}

// RxRectSubscriber allows subscribing to the reactive Rect
type RxRectSubscriber struct {
	C      <-chan Rect
	handle int
	parent *RxRect
}

// Close closes the subscription
func (s *RxRectSubscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()
	go func() {
		select {
		case s.parent.handles <- s.handle:
		default:
		}
	}()
}

// Bind applies all changes to the 'other' RxRect to this name and returns a CancelFunc for
// closure
func (s *RxRect) Bind(ctx context.Context, other *RxRect) context.CancelFunc {
	ctx, cancel := context.WithCancel(ctx)
	go func(ctx context.Context) {
		s2 := other.Subscribe()
		defer s2.Close()
		for {
			select {
			case o := <-s2.C:
				s.Set(o)
			case <-ctx.Done():
				return
			}
		}
	}(ctx)
	return cancel
}
