// Generated by: main
// TypeWriter: rx
// Directive: +gen on Bool_

package rx

import (
	"context"
	sync "sync"
)

// Bool is the reactive wrapper for bool
type Bool struct {
	value       bool
	lock        sync.RWMutex
	handles     chan int
	subscribers []chan<- bool
}

// NewBool creates a new reactive object for the initial value of bool
func NewBool(v bool) *Bool {
	return &Bool{
		value:   v,
		handles: make(chan int, 10),
	}
}

// Get gets the bool
func (rx *Bool) Get() bool {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the bool and notifies subscribers
func (rx *Bool) Set(v bool) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v
	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the bool
func (rx *Bool) Subscribe() *BoolSubscriber {
	c := make(chan bool)
	s := &BoolSubscriber{
		C:      c,
		parent: rx,
	}
	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}
	rx.lock.Unlock()
	return s
}

// BoolSubscriber allows subscribing to the reactive bool
type BoolSubscriber struct {
	C      <-chan bool
	handle int
	parent *Bool
}

// Close closes the subscription
func (s *BoolSubscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()
	go func() {
		select {
		case s.parent.handles <- s.handle:
		default:
		}
	}()
}

// Bind applies all changes to the 'other' Bool to this name and returns a CancelFunc for
// closure
func (s *Bool) Bind(ctx context.Context, other *Bool) context.CancelFunc {
	ctx, cancel := context.WithCancel(ctx)
	s2 := other.Subscribe()
	go func(ctx context.Context) {
		defer s2.Close()
		for {
			select {
			case o := <-s2.C:
				s.Set(o)
			case <-ctx.Done():
				return
			}
		}
	}(ctx)
	return cancel
}
