// generated by genrx -name RxInt16 -type int16 .; DO NOT EDIT

package rx

import (
	"sync"
)

// RxInt16 is the reactive wrapper for int16
type RxInt16 struct {
	value int16
	lock  sync.RWMutex

	handles     chan int
	subscribers []chan<- int16
}

// NewRxInt16 creates a new reactive object for the initial value of int16
func NewRxInt16(v int16) *RxInt16 {
	return &RxInt16{
		value:   v,
		handles: make(chan int, 1),
	}
}

// Get gets the int16
func (rx *RxInt16) Get() int16 {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the int16 and notifies subscribers
func (rx *RxInt16) Set(v int16) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v

	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the int16
func (rx *RxInt16) Subscribe() *RxInt16Subscriber {

	c := make(chan int16)

	s := &RxInt16Subscriber{
		C:      c,
		parent: rx,
	}

	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}

	rx.lock.Unlock()

	return s
}

// RxInt16Subscriber allows subscribing to the reactive int16
type RxInt16Subscriber struct {
	C      <-chan int16
	handle int
	parent *RxInt16
}

// Close closes the subscription
func (s *RxInt16Subscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()

	go func() {
		s.parent.handles <- s.handle
	}()
}
