// Generated by: main
// TypeWriter: rx
// Directive: +gen on Int8_

package rx

import (
	"context"
	sync "sync"
)

// Int8 is the reactive wrapper for int8
type Int8 struct {
	value       int8
	lock        sync.RWMutex
	handles     chan int
	subscribers []chan<- int8
}

// NewInt8 creates a new reactive object for the initial value of int8
func NewInt8(v int8) *Int8 {
	return &Int8{
		value:   v,
		handles: make(chan int, 10),
	}
}

// Get gets the int8
func (rx *Int8) Get() int8 {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the int8 and notifies subscribers
func (rx *Int8) Set(v int8) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v
	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the int8
func (rx *Int8) Subscribe() *Int8Subscriber {
	c := make(chan int8)
	s := &Int8Subscriber{
		C:      c,
		parent: rx,
	}
	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}
	rx.lock.Unlock()
	return s
}

// Int8Subscriber allows subscribing to the reactive int8
type Int8Subscriber struct {
	C      <-chan int8
	handle int
	parent *Int8
}

// Close closes the subscription
func (s *Int8Subscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()
	go func() {
		select {
		case s.parent.handles <- s.handle:
		default:
		}
	}()
}

// Bind applies all changes to the 'other' Int8 to this name and returns a CancelFunc for
// closure
func (s *Int8) Bind(ctx context.Context, other *Int8) context.CancelFunc {
	ctx, cancel := context.WithCancel(ctx)
	s2 := other.Subscribe()
	go func(ctx context.Context) {
		defer s2.Close()
		for {
			select {
			case o := <-s2.C:
				s.Set(o)
			case <-ctx.Done():
				return
			}
		}
	}(ctx)
	return cancel
}
