// Generated by: main
// TypeWriter: rx
// Directive: +gen on Uint32_

package rx

import (
	"context"
	sync "sync"
)

// Uint32 is the reactive wrapper for uint16
type Uint32 struct {
	value       uint16
	lock        sync.RWMutex
	handles     chan int
	subscribers []chan<- uint16
}

// NewUint32 creates a new reactive object for the initial value of uint16
func NewUint32(v uint16) *Uint32 {
	return &Uint32{
		value:   v,
		handles: make(chan int, 10),
	}
}

// Get gets the uint16
func (rx *Uint32) Get() uint16 {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the Uint32 and notifies subscribers
func (rx *Uint32) Set(v uint16) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v
	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the Uint32
func (rx *Uint32) Subscribe() *Uint32Subscriber {
	c := make(chan uint16)
	s := &Uint32Subscriber{
		C:      c,
		parent: rx,
	}
	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}
	rx.lock.Unlock()
	return s
}

// Uint32Subscriber allows subscribing to the reactive uint16
type Uint32Subscriber struct {
	C      <-chan uint16
	handle int
	parent *Uint32
}

// Close closes the subscription
func (s *Uint32Subscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()
	go func() {
		select {
		case s.parent.handles <- s.handle:
		default:
		}
	}()
}

func (s *Uint32) Bind(ctx context.Context, other *Uint32) context.CancelFunc {
	ctx, cancel := context.WithCancel(ctx)
	go func(ctx context.Context) {
		s2 := other.Subscribe()
		defer s2.Close()
		for {
			select {
			case o := <-s2.C:
				s.Set(o)
			case <-ctx.Done():
				return
			}
		}
	}(ctx)
	return cancel
}
