// Generated by: main
// TypeWriter: rx
// Directive: +gen on Uint16_

package rx

import (
	"context"
	sync "sync"
)

// Uint16 is the reactive wrapper for uint16
type Uint16 struct {
	value       uint16
	lock        sync.RWMutex
	handles     chan int
	subscribers []chan<- uint16
}

// NewUint16 creates a new reactive object for the initial value of uint16
func NewUint16(v uint16) *Uint16 {
	return &Uint16{
		value:   v,
		handles: make(chan int, 10),
	}
}

// Get gets the uint16
func (rx *Uint16) Get() uint16 {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the uint16 and notifies subscribers
func (rx *Uint16) Set(v uint16) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v
	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the uint16
func (rx *Uint16) Subscribe() *Uint16Subscriber {
	c := make(chan uint16)
	s := &Uint16Subscriber{
		C:      c,
		parent: rx,
	}
	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}
	rx.lock.Unlock()
	return s
}

// Uint16Subscriber allows subscribing to the reactive uint16
type Uint16Subscriber struct {
	C      <-chan uint16
	handle int
	parent *Uint16
}

// Close closes the subscription
func (s *Uint16Subscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()
	go func() {
		select {
		case s.parent.handles <- s.handle:
		default:
		}
	}()
}

// Bind applies all changes to the 'other' Uint16 to this name and returns a CancelFunc for
// closure
func (s *Uint16) Bind(ctx context.Context, other *Uint16) context.CancelFunc {
	ctx, cancel := context.WithCancel(ctx)
	go func(ctx context.Context) {
		s2 := other.Subscribe()
		defer s2.Close()
		for {
			select {
			case o := <-s2.C:
				s.Set(o)
			case <-ctx.Done():
				return
			}
		}
	}(ctx)
	return cancel
}
