// generated by genrx -name RxUint16 -type uint16 .; DO NOT EDIT

package rx

import (
	"sync"
)

// RxUint16 is the reactive wrapper for uint16
type RxUint16 struct {
	value uint16
	lock  sync.RWMutex

	handles     chan int
	subscribers []chan<- uint16
}

// NewRxUint16 creates a new reactive object for the initial value of uint16
func NewRxUint16(v uint16) *RxUint16 {
	return &RxUint16{
		value:   v,
		handles: make(chan int, 1),
	}
}

// Get gets the uint16
func (rx *RxUint16) Get() uint16 {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the uint16 and notifies subscribers
func (rx *RxUint16) Set(v uint16) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v

	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the uint16
func (rx *RxUint16) Subscribe() *RxUint16Subscriber {

	c := make(chan uint16)

	s := &RxUint16Subscriber{
		C:      c,
		parent: rx,
	}

	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}

	rx.lock.Unlock()

	return s
}

// RxUint16Subscriber allows subscribing to the reactive uint16
type RxUint16Subscriber struct {
	C      <-chan uint16
	handle int
	parent *RxUint16
}

// Close closes the subscription
func (s *RxUint16Subscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()

	go func() {
		s.parent.handles <- s.handle
	}()
}
