// generated by genrx -name RxUint32 -type uint32 .; DO NOT EDIT

package rx

import (
	"sync"
)

// RxUint32 is the reactive wrapper for uint32
type RxUint32 struct {
	value uint32
	lock  sync.RWMutex

	handles     chan int
	subscribers []chan<- uint32
}

// NewRxUint32 creates a new reactive object for the initial value of uint32
func NewRxUint32(v uint32) *RxUint32 {
	return &RxUint32{
		value:   v,
		handles: make(chan int, 1),
	}
}

// Get gets the uint32
func (rx *RxUint32) Get() uint32 {
	rx.lock.RLock()
	defer rx.lock.RUnlock()
	return rx.value
}

// Set sets the uint32 and notifies subscribers
func (rx *RxUint32) Set(v uint32) {
	rx.lock.Lock()
	defer rx.lock.Unlock()
	rx.value = v

	for _, s := range rx.subscribers {
		if s != nil {
			s <- v
		}
	}
}

// Subscribe subscribes to changes on the uint32
func (rx *RxUint32) Subscribe() *RxUint32Subscriber {

	c := make(chan uint32)

	s := &RxUint32Subscriber{
		C:      c,
		parent: rx,
	}

	rx.lock.Lock()
	select {
	case handle := <-rx.handles:
		s.handle = handle
		rx.subscribers[handle] = c
	default:
		rx.subscribers = append(rx.subscribers, c)
		s.handle = len(rx.subscribers) - 1
	}

	rx.lock.Unlock()

	return s
}

// RxUint32Subscriber allows subscribing to the reactive uint32
type RxUint32Subscriber struct {
	C      <-chan uint32
	handle int
	parent *RxUint32
}

// Close closes the subscription
func (s *RxUint32Subscriber) Close() {
	// remove from parent and close channel
	s.parent.lock.Lock()
	close(s.parent.subscribers[s.handle])
	s.parent.subscribers[s.handle] = nil
	s.parent.lock.Unlock()

	go func() {
		s.parent.handles <- s.handle
	}()
}
